# Generated by Django 2.2.3 on 2019-07-18 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsprings', '0002_offspring_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offspring',
            name='baptized',
            field=models.BooleanField(default=True, verbose_name='bautizado'),
        ),
        migrations.AddField(
            model_name='offspring',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='offspring',
            name='father_name',
            field=models.CharField(default='padre', max_length=150, verbose_name='nombre completo del padre'),
        ),
        migrations.AddField(
            model_name='offspring',
            name='home_address',
            field=models.CharField(default='Mi casa', max_length=150, verbose_name='colegio'),
        ),
        migrations.AddField(
            model_name='offspring',
            name='mother_name',
            field=models.CharField(default='madre', max_length=150, verbose_name='nombre completo de la madres'),
        ),
        migrations.AddField(
            model_name='offspring',
            name='school',
            field=models.CharField(default='Las Tablas', max_length=150, verbose_name='colegio'),
        ),
    ]
