# Generated by Django 2.2.3 on 2019-07-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsprings', '0003_auto_20190718_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offspring',
            name='mother_name',
            field=models.CharField(default='madre', max_length=150, verbose_name='nombre completo de la madre'),
        ),
    ]
